import { useEffect, useState, useCallback } from 'react'
import SwaggerUI from 'swagger-ui-react'
import 'swagger-ui-react/swagger-ui.css'
import useDocumentTitle from '../hooks/useDocumentTitle'
import Breadcrumbs from '../components/ui/Breadcrumbs'

/**
 * Live API documentation page for Organisation-related endpoints.
 *
 * Fetches the OpenAPI 3.0 spec from the running backend's
 * /v3/api-docs/organizations endpoint (generated by springdoc-openapi).
 *
 * Dynamic: every time a new @Operation is added to OrganizationController,
 * OrgBrandingController, QuotaController, or TemplateSharingController and
 * the backend restarts, this page automatically reflects the change.
 *
 * Groups available (selectable via the Group dropdown):
 *   organizations — /api/organizations/** + /api/sharing/**
 *   all           — every /api/** endpoint
 */

const CRUMBS = [
  { label: 'Dashboard', to: '/' },
  { label: 'API Documentation' },
]

// In dev, Vite proxies /v3/** → http://localhost:8080/v3/**
// In prod, point directly at the deployed backend origin via VITE_API_ORIGIN env var.
const BACKEND_ORIGIN = import.meta.env.VITE_API_ORIGIN ?? ''

const API_GROUPS = [
  {
    id:    'organizations',
    label: 'Organization Management',
    desc:  'Organizations · Branding · Quotas · Template Sharing',
    url:   `${BACKEND_ORIGIN}/v3/api-docs/organizations`,
    color: 'indigo',
  },
  {
    id:    'pdf-templates',
    label: 'PDF Templates',
    desc:  'Template CRUD · Version history · PDF generation',
    url:   `${BACKEND_ORIGIN}/v3/api-docs/pdf-templates`,
    color: 'violet',
  },
  {
    id:    'email-templates',
    label: 'Email Templates',
    desc:  'Template CRUD · Version history · Send via Resend',
    url:   `${BACKEND_ORIGIN}/v3/api-docs/email-templates`,
    color: 'blue',
  },
  {
    id:    'esign',
    label: 'E-Sign',
    desc:  'Creator · Client signing · Public verification',
    url:   `${BACKEND_ORIGIN}/v3/api-docs/esign`,
    color: 'emerald',
  },
  {
    id:    'all',
    label: 'All Endpoints',
    desc:  'Full API surface — Auth, Users, Sessions, …',
    url:   `${BACKEND_ORIGIN}/v3/api-docs/all`,
    color: 'gray',
  },
]

const COLOR_MAP = {
  indigo: {
    active:   'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-300',
    inactive: 'border-gray-200 dark:border-gray-700 hover:border-indigo-300 text-gray-600 dark:text-gray-400',
    dot:      'bg-indigo-500',
  },
  violet: {
    active:   'border-violet-500 bg-violet-50 dark:bg-violet-900/20 text-violet-700 dark:text-violet-300',
    inactive: 'border-gray-200 dark:border-gray-700 hover:border-violet-300 text-gray-600 dark:text-gray-400',
    dot:      'bg-violet-500',
  },
  blue: {
    active:   'border-blue-500 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300',
    inactive: 'border-gray-200 dark:border-gray-700 hover:border-blue-300 text-gray-600 dark:text-gray-400',
    dot:      'bg-blue-500',
  },
  emerald: {
    active:   'border-emerald-500 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-300',
    inactive: 'border-gray-200 dark:border-gray-700 hover:border-emerald-300 text-gray-600 dark:text-gray-400',
    dot:      'bg-emerald-500',
  },
  gray: {
    active:   'border-gray-500 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200',
    inactive: 'border-gray-200 dark:border-gray-700 hover:border-gray-400 text-gray-600 dark:text-gray-400',
    dot:      'bg-gray-500',
  },
}

/* ── Swagger UI theme overrides injected as a <style> block ── */
const SWAGGER_OVERRIDES = `
  /* Hide the default Swagger UI top bar */
  .swagger-ui .topbar { display: none !important; }

  /* Typography */
  .swagger-ui { font-family: inherit !important; }
  .swagger-ui .info .title { font-size: 1.25rem !important; font-weight: 700 !important; color: #1e1b4b; }
  .swagger-ui .info .description p { font-size: 0.875rem !important; }

  /* Section pills */
  .swagger-ui .opblock-tag { font-size: 0.875rem !important; font-weight: 700 !important; }

  /* Method badges */
  .swagger-ui .opblock .opblock-summary-method {
    border-radius: 0.375rem !important;
    font-size: 0.625rem !important;
    font-weight: 800 !important;
    min-width: 4.5rem !important;
  }

  /* GET */
  .swagger-ui .opblock.opblock-get { border-color: #6366f1 !important; background: #eef2ff !important; }
  .swagger-ui .opblock.opblock-get .opblock-summary-method { background: #6366f1 !important; }

  /* POST */
  .swagger-ui .opblock.opblock-post { border-color: #10b981 !important; background: #ecfdf5 !important; }
  .swagger-ui .opblock.opblock-post .opblock-summary-method { background: #10b981 !important; }

  /* PUT */
  .swagger-ui .opblock.opblock-put { border-color: #f59e0b !important; background: #fffbeb !important; }
  .swagger-ui .opblock.opblock-put .opblock-summary-method { background: #f59e0b !important; }

  /* DELETE */
  .swagger-ui .opblock.opblock-delete { border-color: #ef4444 !important; background: #fef2f2 !important; }
  .swagger-ui .opblock.opblock-delete .opblock-summary-method { background: #ef4444 !important; }

  /* Execute button */
  .swagger-ui .btn.execute { background: #6366f1 !important; border-color: #4f46e5 !important; border-radius: 0.5rem !important; }

  /* Input fields */
  .swagger-ui input[type=text], .swagger-ui textarea {
    border-radius: 0.5rem !important;
    border: 1px solid #e5e7eb !important;
    font-size: 0.8125rem !important;
  }

  /* Response area */
  .swagger-ui .responses-inner { font-size: 0.8125rem !important; }

  /* Remove extra padding */
  .swagger-ui .wrapper { padding: 0 !important; }
`

export default function ApiDocsPage() {
  useDocumentTitle('API Documentation')

  const [selectedGroup, setSelectedGroup] = useState(API_GROUPS[0])
  const [specUrl,       setSpecUrl]       = useState(API_GROUPS[0].url)
  const [backendStatus, setBackendStatus] = useState('checking') // 'checking' | 'online' | 'offline'
  const [lastRefreshed, setLastRefreshed] = useState(null)

  // Check if backend is reachable
  const checkBackend = useCallback(() => {
    fetch(`${BACKEND_ORIGIN}/v3/api-docs/organizations`)
      .then(r => {
        setBackendStatus(r.ok ? 'online' : 'offline')
        if (r.ok) setLastRefreshed(new Date())
      })
      .catch(() => setBackendStatus('offline'))
  }, [])

  useEffect(() => {
    checkBackend()
  }, [checkBackend])

  const handleGroupChange = (group) => {
    setSelectedGroup(group)
    // Force SwaggerUI to re-fetch by toggling URL
    setSpecUrl('')
    setTimeout(() => setSpecUrl(group.url), 50)
  }

  const handleRefresh = () => {
    setBackendStatus('checking')
    const url = selectedGroup.url
    setSpecUrl('')
    setTimeout(() => {
      setSpecUrl(url)
      setBackendStatus('online')
      setLastRefreshed(new Date())
    }, 100)
  }

  return (
    <div className="max-w-7xl mx-auto px-6 py-8">
      <Breadcrumbs items={CRUMBS} />

      {/* ── Header ── */}
      <div className="flex items-start justify-between mt-4 mb-6 gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-bold text-navy dark:text-white">API Documentation</h1>
          <p className="text-sm text-gray-500 mt-1">
            Live reference generated from the running backend. Updates automatically when controllers change.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {/* Backend status pill */}
          <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold
            ${backendStatus === 'online'
              ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300'
              : backendStatus === 'offline'
              ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300'
              : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300'
            }`}>
            <span className={`w-1.5 h-1.5 rounded-full ${
              backendStatus === 'online' ? 'bg-emerald-500 animate-pulse'
              : backendStatus === 'offline' ? 'bg-red-500'
              : 'bg-gray-400 animate-pulse'
            }`} />
            {backendStatus === 'online' ? 'Backend online'
              : backendStatus === 'offline' ? 'Backend offline'
              : 'Checking…'}
          </div>

          {/* Refresh button */}
          <button
            onClick={handleRefresh}
            title="Refresh spec from backend"
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-600
                       text-xs font-semibold text-gray-600 dark:text-gray-300
                       hover:border-indigo-400 hover:text-indigo-600 transition-colors"
          >
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/>
            </svg>
            Refresh
          </button>
        </div>
      </div>

      {/* ── Group selector ── */}
      <div className="flex gap-3 mb-6 flex-wrap">
        {API_GROUPS.map(group => {
          const colors = COLOR_MAP[group.color]
          const isActive = selectedGroup.id === group.id
          return (
            <button
              key={group.id}
              onClick={() => handleGroupChange(group)}
              className={`flex items-start gap-3 px-4 py-3 rounded-xl border-2 text-left transition-all
                ${isActive ? colors.active : colors.inactive}`}
            >
              <span className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${isActive ? colors.dot : 'bg-gray-300 dark:bg-gray-600'}`} />
              <div>
                <p className="text-sm font-bold leading-tight">{group.label}</p>
                <p className={`text-[11px] mt-0.5 ${isActive ? 'opacity-80' : 'text-gray-400 dark:text-gray-500'}`}>
                  {group.desc}
                </p>
              </div>
            </button>
          )
        })}
      </div>

      {/* ── Last refreshed ── */}
      {lastRefreshed && (
        <p className="text-[11px] text-gray-400 mb-4">
          Spec loaded at {lastRefreshed.toLocaleTimeString()} — reflects the live backend
        </p>
      )}

      {/* ── Swagger UI ── */}
      {backendStatus === 'offline' ? (
        <div className="card flex flex-col items-center justify-center py-20 gap-4 text-gray-400">
          <svg className="w-12 h-12 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5}
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/>
          </svg>
          <div className="text-center">
            <p className="text-sm font-semibold text-gray-600 dark:text-gray-400">Backend not reachable</p>
            <p className="text-xs text-gray-400 mt-1">
              Make sure <code className="bg-gray-100 dark:bg-gray-700 px-1 rounded">braify-web-services</code> is running on port 8080.
            </p>
          </div>
          <button onClick={handleRefresh} className="btn btn-secondary text-xs">
            Try again
          </button>
        </div>
      ) : (
        <div className="card p-0 overflow-hidden">
          {/* Inject style overrides */}
          <style>{SWAGGER_OVERRIDES}</style>

          {/* Info banner */}
          <div className="flex items-center gap-3 px-5 py-3 bg-indigo-50 dark:bg-indigo-900/20 border-b border-indigo-100 dark:border-indigo-800">
            <svg className="w-4 h-4 text-indigo-500 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
            <p className="text-xs text-indigo-700 dark:text-indigo-300">
              Click <strong>Authorize</strong> and paste your JWT token to test endpoints directly from this page.
              Get your token from <code className="bg-indigo-100 dark:bg-indigo-800 px-1 rounded">POST /api/auth/login</code>.
            </p>
          </div>

          {/* Swagger UI mount point */}
          <div className="p-4">
            {specUrl && (
              <SwaggerUI
                url={specUrl}
                docExpansion="list"
                defaultModelsExpandDepth={1}
                displayRequestDuration={true}
                filter={true}
                tryItOutEnabled={true}
                requestInterceptor={(req) => {
                  // Auto-inject stored JWT so "Try it out" works without manual paste
                  const token = localStorage.getItem('pdf-builder-token')
                  if (token && !req.headers?.Authorization) {
                    req.headers = req.headers || {}
                    req.headers.Authorization = `Bearer ${token}`
                  }
                  return req
                }}
              />
            )}
          </div>
        </div>
      )}
    </div>
  )
}
